
  CREATE TABLE ACTIVIDAD (ACT NUMBER(3,0), UD CHAR(2), MOD CHAR(4), DESC_ACT VARCHAR2(200), FECHA_INI DATE, FECHA_FIN DATE);

  
  CREATE TABLE PRUEBA (PRU CHAR(7), DESC_PRU VARCHAR2(200), FECHA DATE);
  
  
  CREATE TABLE AL_PRU (ALUMNO CHAR(9), PRU CHAR(7), CE CHAR(1), PUNTOS NUMBER(5,2) DEFAULT 0);

  
  CREATE TABLE AL_ACT (ALUMNO CHAR(9), ACT NUMBER(3,0), UD CHAR(2), MOD CHAR(4), CE CHAR(1), PUNTOS NUMBER(5,2) DEFAULT 0);

  
  CREATE TABLE ALUMNO (DNI CHAR(9), FECHA_NAC DATE, EMAIL VARCHAR2(50), NOMBRE VARCHAR2(20), APELLIDOS VARCHAR2(30));

  
  CREATE TABLE CE (CE CHAR(1), RA CHAR(2), MOD CHAR(4), DESC_CE VARCHAR2(200));

  
  CREATE TABLE IMPARTE (PROF CHAR(9), MOD CHAR(4), CURSO DATE);

  
  CREATE TABLE MATRICULA (ALUMNO CHAR(9), MOD CHAR(4), CURSO DATE);

  
  CREATE TABLE MODULO (CODIGO CHAR(4), NOMBRE VARCHAR2(60), HORAS NUMBER(3,0), NIVEL CHAR(3));

  
  CREATE TABLE PROFESOR (DNI CHAR(9), NOMBRE VARCHAR2(50), APELLIDOS VARCHAR2(50));

  
  CREATE TABLE RA (RA CHAR(2), MOD CHAR(4), DESC_RA VARCHAR2(200));

  
  CREATE TABLE UD (UD CHAR(2), MOD CHAR(4), NOMBRE VARCHAR2(100), HORAS NUMBER(3,0));
  
  
  CREATE TABLE UD_PRUEBA (UD CHAR(2), PRU NUMBER(3,0));
  
  
  CREATE TABLE ACT_CE (ACT NUMBER(3,0), CE CHAR(1), MOD CHAR(4), PMAX NUMBER(5,2));
