-- CREAMOS UN DISPARADOR QUE SE ENCARGA DE ASOCIAR A UN ALUMNO A CADA
-- UNO DE LOS CRITERIOS DE EVALUACIÓN DE UNA ACTIVIDAD
CREATE OR REPLACE TRIGGER PON_AL_ACT
AFTER INSERT ON ACT_CE
FOR EACH ROW
DECLARE
  CURSOR CUR_ALUMNOS IS SELECT A.DNI, M.MODU FROM ALUMNO A, MATRICULA M
  WHERE A.DNI=M.ALU;
BEGIN
  FOR V_ALU IN CUR_ALUMNOS LOOP
    IF V_ALU.MODU = :NEW.MODU THEN
      INSERT INTO AL_ACT (ALU,ACT,UD,MODU,CE,RA) VALUES
      (V_ALU.DNI, :NEW.ACT, :NEW.UD, :NEW.MODU, :NEW.CE, :NEW.RA);
    END IF;
  END LOOP;
END;
/
