--INSERTAMOS PARA UNA ACTIVIDAD, UN 0 EN TODAS LAS NOTAS
--PODRÍA CONSTRUIRSE UN CURSOR DE TAL FORMA QUE CADA VEZ QUE SE AÑADE A ACT_CE
--UN CE Y SU PUNTUACIÓN MÁXIMA, A CADA ALUMNO MATRICULADO SE LE INSERTE UN CERO POR DEFECTO
INSERT INTO AL_ACT SELECT DNI, ACT, UD, MATRICULA.MODU, CE, 0, RA FROM ALUMNO, MATRICULA, ACT_CE
WHERE ALUMNO.DNI=MATRICULA.ALU AND MATRICULA.MODU = ACT_CE.MODU
AND MATRICULA.MODU = '0227'
AND UD='04' AND RA='03'
ORDER BY APELLIDOS, UD, ACT, CE;
--OTRO DISPARADOR NECESARIO ES QUE UN ALUMNO NO PUEDE TENER MÁS NOTA EN UN CE
--QUE EL MÁXIMO ESTABLECIDO PARA ESA ACTIVIDAD
