--------------------------------------------------------
-- Archivo creado  - jueves-enero-19-2017   
--------------------------------------------------------
REM INSERTING into CALIFICACIONES1.ALUMNO
SET DEFINE OFF;
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('48121406R',to_date('17/08/96','DD/MM/RR'),'javierbro1234@gmail.com','Francisco Javier','Benítez Rodríguez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30225816K',to_date('23/09/87','DD/MM/RR'),'j.carmona.leiva@gmail.com','Javier','Carmona Leiva');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('29540211T',to_date('08/11/96','DD/MM/RR'),'sacave96@gmail.com','Salvador','Castillo Vergara');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('53768064K',to_date('01/08/90','DD/MM/RR'),'jonathanconde1990@gmail.com','Jonathan','Conde Sobrá');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('15454405S',to_date('01/01/98','DD/MM/RR'),'juanmiguelfp1@gmail.com','Juan Miguel','Delgado García');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('49060166Q',to_date('20/05/91','DD/MM/RR'),'noeclarinete20@gmail.com','Noé','Domínguez López');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30248114D',to_date('11/08/94','DD/MM/RR'),'alvarof8@hotmail.com','Álvaro Manuel','Fernández Moscoso');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('53771238K',to_date('18/12/94','DD/MM/RR'),'maforerof@gmail.com','Miguel Ángel','Forero Fernández');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('29536838P',to_date('09/07/97','DD/MM/RR'),'franfranco503@gmail.com','Francisco Javier','Franco Toril');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77869052E',to_date('25/02/97','DD/MM/RR'),'agh2997@gmail.com','Abraham','Garrido Muñoz');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30249042V',to_date('16/09/92','DD/MM/RR'),'beiroa92@gmail.com','Alejandro','Beiroa Pérez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('47429304S',to_date('04/11/97','DD/MM/RR'),'thewalkerofdreams@gmail.com','Yeray Manuel','Campanario Fernández');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30270128N',to_date('25/10/97','DD/MM/RR'),'moicasas2597@gmail.com','Moisés de las','Casas Medina');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30234068Q',to_date('29/06/86','DD/MM/RR'),'fernandodavid86@gmail.com','Fernando David','Castillo Oria');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('28624483V',to_date('16/01/88','DD/MM/RR'),'javierdorado9@gmail.com','Javier','Dorado Millán');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30231059C',to_date('09/06/93','DD/MM/RR'),'M.J.Informatica700@gmail.com','Mario','Jara Rivera');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77924856M',to_date('17/10/97','DD/MM/RR'),'jmaraya97@gmail.com','Juan','Martín Ayala');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77866021G',to_date('04/08/95','DD/MM/RR'),'manuel.ramos.torres@gmail.com','Manuel','Ramos Torres');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('48819882J',to_date('27/03/82','DD/MM/RR'),'ricardo_romero_82@hotmail.com','Ricardo','Romero Paredes');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77809921R',to_date('23/01/88','DD/MM/RR'),'macnolillo@gmail.com','José Manuel','Suárez Vargas');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30263906T',to_date('27/10/92','DD/MM/RR'),'migueltrujillonavarro@gmail.com','Miguel','Trujillo Navarro');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('28894224Z',to_date('27/04/69','DD/MM/RR'),'franciscovallesaez69@gmail.com','Francisco','Valle Sáez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('29581852B',to_date('20/05/97','DD/MM/RR'),'gradomedio1516@gmail.com','Luis Ángel','Zurita Ávalos');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('47393737Y',to_date('17/06/95','DD/MM/RR'),'blastru88@gmail.com','Blas','Báez Pérez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('20092630Z',to_date('30/01/96','DD/MM/RR'),'Dani96alcala@gmail.com','Daniel','Hernández Jiménez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('53772555G',to_date('02/09/95','DD/MM/RR'),'juanjo113@gmail.com','Juan José','Hernández Valero');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('28845713X',to_date('11/09/95','DD/MM/RR'),'alvarofcogs@gmail.com','Álvaro Francisco','Juan Fernández');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('49521305M',to_date('23/07/97','DD/MM/RR'),'lorence.alejandro@gmail.com','Alejandro','Lorence Gutiérrez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('29516787J',to_date('06/06/97','DD/MM/RR'),'TheMendezz@gmail.com','José Manuel','Méndez Melgar');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('53772567Q',to_date('09/05/92','DD/MM/RR'),'lola.moreno.maldonado@gmail.com','María Dolores','Moreno Maldonado');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('44242487D',to_date('13/07/95','DD/MM/RR'),'davidmorenoviz@gmail.com','David','Moreno Vizcaíno');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('111111111',to_date('30/12/99','DD/MM/RR'),'jmorentee@gmail.com','José','Morente Lanza');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('28849908L',to_date('07/11/93','DD/MM/RR'),'joni.sanchez711@gmail.com','Jonatan','Sánchez Díaz');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77934053W',to_date('25/02/98','DD/MM/RR'),'antsan.nepu@gmail.com','Antonio','Sánchez Espinosa');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('X5856765E',to_date('12/01/83','DD/MM/RR'),'dsalvesp@gmail.com','Diego Sebastián','Alves Pérez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30697268L',to_date('27/12/96','DD/MM/RR'),'jcb273@hotmail.es','Joaquín','Cabezas Berjillos');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('49091067M',to_date('13/07/92','DD/MM/RR'),'v.laura.cannero@gmail.com','Laura','Cañero Amoreti');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30258483M',to_date('08/11/94','DD/MM/RR'),'yuyon81194@gmail.com','Pablo','Cayuela Riquel');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('49033563R',to_date('26/10/90','DD/MM/RR'),'fdoferrete@outlook.com','Fernando','Ferrete Poza');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77851937L',to_date('22/01/96','DD/MM/RR'),'manu.gandul@gmail.com','Manuel','Gandul Pérez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('20064897L',to_date('16/06/92','DD/MM/RR'),'agarciacaro@gmail.com','Alejandro','García Caro');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30239009N',to_date('22/05/93','DD/MM/RR'),'mario.garcia.93@gmail.com','Mario','García Cúder');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('20062450X',to_date('13/01/93','DD/MM/RR'),'danigonzalezrivera@gmail.com','Daniel','González Rivera');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77860416B',to_date('14/04/94','DD/MM/RR'),'manueljimenezgimenez94@gmail.com','Manuel','Jiménez Giménez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77849671F',to_date('08/09/89','DD/MM/RR'),'julian_lizundia@hotmail.com','Julián Camilo','Lizundia Fernández');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('48121516L',to_date('09/02/96','DD/MM/RR'),'fcojavier069@gmail.com','Francisco Javier','Madroñal Guillén');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('29506735N',to_date('19/04/94','DD/MM/RR'),'josenum94@gmail.com','José','Núñez Molina');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30271969J',to_date('08/12/96','DD/MM/RR'),'DPMpulido@gmail.com','Daniel','Pulido Muñoz');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30223693Z',to_date('19/06/91','DD/MM/RR'),'gonzalo.pulido.r@gmail.com','Gonzalo','Pulido Rodríguez');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('28634139J',to_date('05/04/92','DD/MM/RR'),'pse541992@gmail.com','Pablo','Sánchez Espada');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77814542E',to_date('24/11/89','DD/MM/RR'),'aletorres89@gmail.com','Alejandro','Torres Serrano');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('Y0805173A',to_date('29/04/95','DD/MM/RR'),'eldar.95@hotmail.com','Eldar','Utyamishev ');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('77818618G',to_date('19/08/90','DD/MM/RR'),'tovarrenzo@gmail.com','Renzo Ademir','Vásquez Tovar');
Insert into CALIFICACIONES1.ALUMNO (DNI,FECHA_NAC,EMAIL,NOMBRE,APELLIDOS) values ('30256952S',to_date('31/08/91','DD/MM/RR'),'luisitovg36@gmail.com','Luis','Vázquez Gerena');
