--------------------------------------------------------
-- Archivo creado  - jueves-enero-19-2017   
--------------------------------------------------------
REM INSERTING into CALIFICACIONES1.RA
SET DEFINE OFF;
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('04','0377','AUTOMATIZA TAREAS DE ADMINISTRACIÓN DEL GESTOR DESCRIBIÉNDOLAS Y UTILIZANDO GUIONES DE SENTENCIAS');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('05','0377','OPTIMIZA EL RENDIMIENTO DEL SISTEMA APLICANDO TÉCNICAS DE MONITORIZACIÓN Y REALIZANDO ADAPTACIONES');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('01','0377','IMPLANTA SISTEMAS GESTORES DE BASES DE DATOS ANALIZANDO SUS CARACTERÍSTICAS Y AJUSTÁNDOSE A LOS REQUERIMIENTOS DEL SISTEMA');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('02','0377','CONFIGURA EL SISTEMA GESTOR DE BASES DE DATOS INTERPRETANDO LAS ESPECIFICACIONES TÉCNICAS Y LOS REQUISITOS DE EXPLOTACIÓN');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('03','0377','IMPLANTA MÉTODOS DE CONTROL DE ACCESO UTILIZANDO ASISTENTES, HERRAMIENTAS GRÁFICAS Y COMANDOS DEL LENGUAJE DEL SISTEMA GESTOR');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('06','0377','APLICA CRITERIOS DE DISPONIBILIDAD ANALIZÁNDOLOS Y AJUSTANDO LA CONFIGURACIÓN DEL SISTEMA GESTOR');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('01','0372','RECONOCE LOS ELEMENTOS DE LAS BASES DE DATOS ANALIZANDO SUS FUNCIONES Y VALORANDO LA UTILIDAD DE SISTEMAS GESTORES');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('02','0372','DISEÑA MODELOS LÓGICOS NORMALIZADOS INTERPRETANDO DIAGRAMAS ENTIDAD/RELACIÓN');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('03','0372','REALIZA EL DISEÑO FÍSICO DE BASES DE DATOS UTILIZANDO ASISTENTES, HERRAMIENTAS GRÁFICAS Y EL LENGUAJE DE DEFINICIÓN DE DATO');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('04','0372','CONSULTA LA INFORMACIÓN ALMACENADA MANEJANDO ASISTENTES, HERRAMIENTAS GRÁFICAS Y EL LENGUAJE DE MANIPULACIÓN DE DATOS');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('05','0372','MODIFICA LA INFORMACIÓN ALMACENADA UTILIZANDO ASISTENTES, HERRAMIENTAS GRÁFICAS Y EL LENGUAJE DE MANIPULACIÓN DE DATOS');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('06','0372','EJECUTA TAREAS DE ASEGURAMIENTO DE LA INFORMACIÓN, ANALIZÁNDOLAS Y APLICANDO MECANISMOS DE SALVAGUARDA Y TRANSFERENCIA');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('01','0227','INSTALAR SERVICIOS DE CONFIGURACIÓN DINÁMICA, DESCRIBIENDO SUS CARACTERÍSTICAS Y APLICACIONES');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('02','0227','NSTALAR SERVICIOS DE RESOLUCIÓN DE NOM­BRES, DESCRIBIENDO SUS CARACTERÍSTICAS Y APLICACIONES');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('03','0227','INSTALAR SERVICIOS DE TRANSFERENCIA DE FICHEROS, DESCRIBIENDO SUS CARACTERÍSTICAS Y APLICA­CIONES');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('04','0227','GESTIONAR SERVIDORES DE CORREO ELECTRÓNICO IDENTIFICANDO REQUERIMIENTOS DE UTILIZACIÓN Y APLICANDO CRITERIOS DE CONFIGURACIÓN');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('05','0227','GESTIONAR SERVIDORES WEB IDENTIFICANDO RE­QUERIMIENTOS DE UTILIZACIÓN Y APLICANDO CRITERIOS DE CONFIGURACIÓN');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('06','0227','GESTIONAR MÉTODOS DE ACCESO REMOTO DESCRI­BIENDO SUS CARACTERÍSTICAS E INSTALANDO LOS SERVICIOS CORRESPONDIENTES');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('07','0227','DESPLEGAR REDES INALÁMBRICAS SEGURAS JUSTIFI­CANDO LA CONFIGURACIÓN ELEGIDA Y DESCRIBIENDO LOS PROCEDIMIENTOS DE IMPLANTACIÓN');
Insert into CALIFICACIONES1.RA (RA,MODU,DESC_RA) values ('08','0227','ESTABLECER EL ACCESO DESDE REDES LOCALES A REDES PÚBLICAS IDENTIFICANDO POSIBLES ESCE­NARIOS Y APLICANDO SOFTWARE ESPECÍFICO');
