--------------------------------------------------------
-- Archivo creado  - jueves-enero-19-2017   
--------------------------------------------------------
REM INSERTING into CALIFICACIONES1.UD
SET DEFINE OFF;
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('01','0372','INTRODUCCIÓN A LAS BASES DE DATOS','4', '01');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('02','0372','EL MODELO ENTIDAD-RELACIÓN','18','02');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('03','0372','TRANSFORMACIÓN DEL MODELO ENTIDAD-RALACIÓN AL MODELO RELACIONAL','36','02');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('04','0372','ELABORACIÓN DEL DISEÑO FÍSICO','36','03');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('05','0372','REALIZACIÓN DE CONSULTAS','26','04');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('06','0372','MODIFICACIÓN DE LOS DATOS','36','05');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('07','0372','PROGRAMACIÓN DE GUIONES','36','05');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('01','0377','INSTALACIÓN DE UN SISTEMA GESTOR DE BASES DE DATOS','4','01');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('02','0377','CONFIGURACIÓN DE UN SISTEMA GESTOR DE BASES DE DATOS','12','02');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('03','0377','ACCESO A LA INFORMACIÓN','16','03');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('04','0377','ADMINISTRACIÓN DE TAREAS. CONSTRUCCIÓN DE GUIONES DE ADMINISTRACIÓN','18','04');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('05','0377','OPTIMIZACIÓN DEL RENDIMIENTO DEL SISTEMA','6','05');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('06','0377','APLICACIÓN DE LOS CRITERIOS DE DISPONIBILIDAD. BASES DE DATOS DISTRIBUIDAS Y REPLICADAS','7','06');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('01','0227','SERVICIO DHCP','21','01');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('02','0227','SERVICIO DNS','23','02');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('03','0227','SERVICIO DE ACCESO REMOTO','21','06');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('04','0227','SERFICIO DE TRANSFERENCIA DE FICHEROS','20','03');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('05','0227','SERVICIO DE CORREO ELECTRÓNICO','20','04');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('06','0227','SERVICIO WEB','21','05');
Insert into CALIFICACIONES1.UD (UD,MODU,NOMBRE,HORAS,RA) values ('07','0227','ACCESO A REDES PÚBLICAS','21','08');
