--PUNTOS JUGADOS EN EN MÓDULO XXXX, RA XX
CREATE OR REPLACE VIEW JUGADOS_0377_04 AS select ce.modu, ce.ra, ce.ce, ce.desc_ce, ce.pmax, sum(nvl(act_ce.pmax,0)) as jugados
from ce, act_ce
where ce.ce = act_ce.ce(+) and ce.ra=act_ce.ra(+) and ce.modu=act_ce.modu(+)
and ce.modu='0377' and ce.ra='04'
group by ce.modu, ce.ra, ce.ce, ce.desc_ce, ce.pmax
order by ce.ce;
--VISTA QUE PERMITE OBTENER LA NOTA DE TODOS LOS ALUMNOS EN TODOS LOS CE
--PRIMERO LOS PUNTOS QUE VIENEN DE ACTIVIDADES. DESPUÉS LOS QUE VIENEN DE LAS
--PRUEBAS (RESULTADO DE UNA UNIÓN)
CREATE VIEW AL_CE AS
SELECT APELLIDOS, NOMBRE, MODU, RA, CE, SUM(PUNTOS) PUNTOS FROM ALU_ACT
GROUP BY APELLIDOS, NOMBRE, MODU, RA, CE
UNION 
SELECT APELLIDOS, NOMBRE, MODU, RA, CE, SUM(PUNTOS) PUNTOS FROM ALU_PRU
GROUP BY APELLIDOS, NOMBRE, MODU, RA, CE
ORDER BY APELLIDOS, NOMBRE, MODU, RA, CE;
--VISTA QUE PERMITE OBTENER LA NOTA DE TODOS LOS ALUMNOS EN TODOS LOS CE
--HACIENDO USO DE LA VISTA AL_CE PARA PODER FUSIONAR LOS PUNTOS QUE VIENEN DE
--ACTIVIDADES Y DE PRUEBAS
CREATE VIEW ALU_CE AS
SELECT APELLIDOS, NOMBRE, MODU, RA, CE, SUM(PUNTOS) PUNTOS FROM AL_CE
GROUP BY APELLIDOS, NOMBRE, MODU, RA, CE
ORDER BY APELLIDOS, NOMBRE, MODU, RA, CE;
--VISTA QUE PERMITE OBTENER LA NOTA DE TODOS LOS ALUMNOS EN TODOS LOS CE
--HACIENDO USO DE LA VISTA AL_CE PARA PODER FUSIONAR LOS PUNTOS QUE VIENEN DE
--ACTIVIDADES Y DE PRUEBAS UNIDO A LA PUNTUACIÓN MÁXIMA DE CADA CE
CREATE VIEW ALU_CE_PMAX AS
SELECT APELLIDOS, NOMBRE, AL_CE.MODU, AL_CE.RA, CE.CE, PMAX, SUM(PUNTOS) PUNTOS FROM AL_CE, CE
WHERE AL_CE.CE = CE.CE AND AL_CE.RA=CE.RA AND AL_CE.MODU=CE.MODU
GROUP BY APELLIDOS, NOMBRE, AL_CE.MODU, AL_CE.RA, CE.CE, PMAX
ORDER BY APELLIDOS, NOMBRE, AL_CE.MODU, AL_CE.RA, CE.CE;

--EN ESTA VISTA SE MUESTRA LA SUMA DE PUNTOS OBTENIDOS Y EL MÁXIMO QUE SE PODÍA
--OBTENER EN CADA RA
CREATE VIEW ALU_PUNTOS_RA AS SELECT APELLIDOS, NOMBRE, MODU, RA, SUM(PMAX) MAX_RA, SUM(PUNTOS) PUNTOS
FROM ALU_CE_PMAX
GROUP BY APELLIDOS, NOMBRE, MODU, RA
ORDER BY APELLIDOS, NOMBRE, MODU, RA;
